### ISSUE TITLE
Crear las entidades de lectura y extracción del XML

### ISSUE THREAD

**Issue by EstebanCardenas27** [training-webFactura/ejercicio_3#3]

**Comment by niba291** [comment]
### Added
- https://github.com/training-webFactura/ejercicio_3
    - Se han creados los modelos de las tabla de la bd.

- Desarrollador Responsable: Nibaldo Chavez.

### Entidades

### Clases
- No presentaron cambios.

### Controladores
- No presentaron cambios.

### Formularios
- No presentaron cambios.

### Comandos
- No presentaron cambios.

### Entidades
- src/Entity/TIPOENVIO.php
- src/Entity/LOG.php
- src/Entity/CABEZA.php
- src/Entity/IDENTIFICACION.php
- src/Entity/ORIGENTRANSPALMACENAJE.php
- src/Entity/ANTECEDENTESFINANCIEROS.php
- src/Entity/TOTALES.php
- src/Entity/RESPUESTA.php
- src/Entity/ITEMS.php
- src/Entity/OBSERVACIONESITEM.php
- src/Entity/CUENTASITEM.php
- src/Entity/VISTOSBUENOS.php
- src/Entity/BULTOS.php
- src/Entity/BULTO.php
- src/Entity/CUENTASYVALORES.php
- src/Entity/CUENTASGIRO.php

### Vistas
- No presentaron cambios.

### Repositorios
- No presentaron cambios.

### Eventos
- No presentaron cambios.

### Base de datos
- No presentaron cambios.

### Rutas
- No presentaron cambios.
____________________________________________________________________________________________________________________
