### ISSUE TITLE
V1.0.7: "Crear Controlador genérico"

### ISSUE THREAD

**Issue by EstebanCardenas27** [training-webFactura/ejercicio_3#4]

**Comment by niba291** [comment]
### Added
- https://github.com/training-webFactura/ejercicio_3
    - Se han creados los modelos de las tabla de la bd.

- Desarrollador Responsable: Nibaldo Chavez.

### Entidades

### Clases
- src/AppBundle/Model/NormalizaArray.php
    - Se ha agregado nueva clase para limpiar y normalizar del xml
        - func: NormalizaArray

### Controladores
- src/AppBundle/Controller/Upload_XmlController.php
    - Se ha agregado nueva ruta para subir archivo

### Formularios
- No presentaron cambios.

### Comandos
- No presentaron cambios.

### Entidades
- src/Entity/Document.php
    
### Vistas
- No presentaron cambios.

### Repositorios
- No presentaron cambios.

### Eventos
- No presentaron cambios.

### Base de datos
- No presentaron cambios.

### Rutas
- No presentaron cambios.
____________________________________________________________________________________________________________________
