### ISSUE TITLE
V1.0.11:"Crear Controlador Exportar"

### ISSUE THREAD

**Issue by EstebanCardenas27** [training-webFactura/ejercicio_3#7]
Realizar la capa de controladores para gestionar la exportación de datos desde la BD a un archivo xml.

**Comment by niba291** [comment]
### Added
- https://github.com/training-webFactura/ejercicio_3
    - Se han agregado funcionalidad al controlador y exportarlo.

- Desarrollador Responsable: Nibaldo Chavez.

### Entidades

### Clases
- src/AppBundle/Model/XmlModel.php
    - Se ha agregado nueva clase para limpiar y normalizar del xml
       - func: ExportXmlFile

### Controladores
- src/AppBundle/Controller/Upload_XmlController.php
    - Se ha agregado nueva ruta para subir archivo
       - exportXmlAction 

### Formularios
- No presentaron cambios.

### Comandos
- No presentaron cambios.

### Entidades
- No presentaron cambios.
    
### Vistas
- No presentaron cambios.

### Repositorios
- No presentaron cambios.

### Eventos
- No presentaron cambios.

### Base de datos
- No presentaron cambios.

### Rutas
- No presentaron cambios.
____________________________________________________________________________________________________________________
